config/routes.rb
Rails.application.routes.draw do
  root 'comments#index'
  resources :comments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :films
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film, optional: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true,
            length: { minimum: 3, maximum: 20 },
            uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.valid?
      @comment.save

      flash[:success] = 'Comment has been created!'
      redirect_to @comment
    else
      flash[:danger] = 'Something went wrong.'
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = 'Comment has been updated!'

      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/films_controller.rb
require 'uri'

# Creates, show, update and delete articles
class FilmsController < ApplicationController
  before_action :find_film, only: %i[show update edit destroy]
  before_action :film_attributes, only: %i[show]

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      redirect_to @film
    else
      render 'new'
    end
  end

  def index
    @films = Film.all
  end

  def show; end

  def edit; end

  def update
    if @film.update(film_params)
      redirect_to @film
    else
      render 'edit'
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path
  end

  private

  def film_params
    params.require(:film).permit(:title)
  end

  def find_film
    @film = Film.find(params[:id])
  end

  def film_attributes
    @film.description = ImdbService.response(CGI.escape(@film.title))['Plot']
    @film.image = ImdbService.response(CGI.escape(@film.title))['Poster']
    @film.director = ImdbService.response(CGI.escape(@film.title))['Director']
    @film.actors = ImdbService.response(CGI.escape(@film.title))['Actors']
    @film.imdb_rating = ImdbService.response(CGI.escape(@film.title))['imdbRating']
    @film.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class='container'>
  <h1>Edit Comment</h1>

  <%= form_with model: @comment do |form| %>
    <div>
      <%= form.label :body %><br>
      <%= form.text_field :body, class: "form-control" %>
      <% @comment.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <br>
    <div>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class='container'>
  <h1>Comments</h1>

  <ul class="list-group">
    <% @comments.each do |comment| %>
      <li class="list-group-item">
        <%= link_to comment.id, comment %> -
        <%= comment.body %>
      </li>
    <% end %>
  </ul>
  <br>
  <%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary' %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <h1>New Comment</h1>
  <div class="form-group">
    <%= form_with model: @comment do |form| %>
      <% if @comment.errors.any? %>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
      <div>
        <%= form.label :body %><br>
        <%= form.text_area :body, class: "form-control" %>
      </div>
      <br>
      <div>
        <%= form.submit class: "btn btn-primary", method: 'get', remote: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<div class='container'>
  <h1>Comment</h1>

  <h3>Id: <%= @comment.id %></h3>
  <h3>Body: <%= @comment.body %></h3>

  <%= link_to 'Delete', comment_path(@comment), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_comment_path(@comment), class: 'btn btn-primary' %>
  <br>
  <br>
  <%= link_to 'Comments', comments_path, class: 'btn btn-info' %>
</div>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/films/index.html.erb
<div class='container'>
  <% @films.each do |film| %>
  <div class="card mb-3">
    <%= image_tag "#{film.image}", class: "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to film.title, film_path(film) %></h5>
      <p class="card-text"><%= truncate(film.description, length: 100 ) %></p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <% end %>
</div>

app/views/films/new.html.erb
<div>
  <%= form_with(model: @film, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Title' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/films/show.html.erb
<div>
  <h1><%= @film.title %></h1>
</div>
<div>
  <%= @film.description %>
</div>
<div>
  <%= @film.imdb_rating %>
</div>
<div>
  <%= @film.director %>
</div>
<div>
<%= @film.actors %>
</div>

<%= image_tag "#{@film.image}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCinemaRating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
    
    <%= yield %>
  
  </body>
</html>